### ISSUE TITLE
example request: minimal-http-client-post

### ISSUE THREAD

**Issue by nospamcalfee** [ayosec/libwebsockets#1]
Your help with the http server post stuff was great. And the new minimal examples really helped, so I got that working. 

Now my next step is for my app to be able to POST json data from system to system.  Your two existing minimal clients do GETs, and I don't understand how to send data in the first half of a client POST request. It appears it may be as simple as building up a proper lws_client_connect_info structure. Doing the client post write before getting back a response is not obvious.

Thanks, Steve

**Comment by ayosec** [comment]
Hi @nospamcalfee,

Unfortunately, I don't know how to solve your issue. This repository was a fork to keep some changes that I found somewhere (I can't remember where). And, to be honest, I'm not sure why this repository even exists :).

The real repository for the project is https://github.com/warmcat/libwebsockets/ . In their README you can see a [*Support* section](https://github.com/warmcat/libwebsockets/#support), where you can get some links to ask questions. Hope this helps.
